{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "4c780bd6-5ede-4be3-85cd-1b8e5fda3988",
   "metadata": {},
   "outputs": [],
   "source": [
    "# =============================================================================\n",
    "# Standard Library\n",
    "# =============================================================================\n",
    "import re\n",
    "import string\n",
    "from nltk.corpus import stopwords\n",
    "\n",
    "# =============================================================================\n",
    "# Data Processing\n",
    "# =============================================================================\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "97e1e38c-39df-4271-b406-56bf81a040f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# =============================================================================\n",
    "# Load the processed dataset\n",
    "# =============================================================================\n",
    "dataset = pd.read_csv(\"cleaned_dataset.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "71cd4328-74ff-467e-a6b0-8effbd1dbd24",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>semantic_text</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Question: - what are the dimensions of this it...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Question: how much booze can it hold?\\n\\nAnswe...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Question: will this case fit nokia lumia 520\\n...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Question: when folded in the sitting position,...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Question: how long should i leave this on to g...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                       semantic_text\n",
       "0  Question: - what are the dimensions of this it...\n",
       "1  Question: how much booze can it hold?\\n\\nAnswe...\n",
       "2  Question: will this case fit nokia lumia 520\\n...\n",
       "3  Question: when folded in the sitting position,...\n",
       "4  Question: how long should i leave this on to g..."
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Semantic Text Preprocessing\n",
    "# =============================================================================\n",
    "# Clean text for semantic embedding models\n",
    "# =============================================================================\n",
    "\n",
    "def clean_text_semantic(text):\n",
    "    \"\"\"\n",
    "    Clean text while preserving semantic meaning.\n",
    "    \"\"\"\n",
    "\n",
    "    # Convert to string\n",
    "    text = str(text)\n",
    "\n",
    "    # Convert text to lowercase\n",
    "    text = text.lower()\n",
    "\n",
    "    # Remove HTML tags\n",
    "    text = re.sub(r\"<.*?>\", \" \", text)\n",
    "\n",
    "    # Remove URLs\n",
    "    text = re.sub(r\"http\\S+|www\\S+\", \" \", text)\n",
    "\n",
    "    # Remove email addresses\n",
    "    text = re.sub(r\"\\S+@\\S+\", \" \", text)\n",
    "\n",
    "    # Remove extra whitespace\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "\n",
    "    # Remove leading and trailing spaces\n",
    "    text = text.strip()\n",
    "\n",
    "    return text\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# Create semantic text for embedding generation\n",
    "# =============================================================================\n",
    "\n",
    "dataset[\"semantic_text\"] = (\n",
    "    \"Question: \"\n",
    "    + dataset[\"QuestionText\"].apply(clean_text_semantic)\n",
    "    + \"\\n\\nAnswer: \"\n",
    "    + dataset[\"AnswerText\"].apply(clean_text_semantic))\n",
    "\n",
    "# Preview semantic text\n",
    "dataset[[\"semantic_text\"]].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "aaa8b797-9abe-4439-9858-77533265e78a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Lexical (BM25) Text Preprocessing\n",
    "# =============================================================================\n",
    "# Clean text for BM25 lexical retrieval\n",
    "# =============================================================================\n",
    "\n",
    "def clean_text_bm25(text):\n",
    "    \"\"\"\n",
    "    Clean text for lexical search.\n",
    "    \"\"\"\n",
    "\n",
    "    # Convert to string\n",
    "    text = str(text)\n",
    "\n",
    "    # Convert text to lowercase\n",
    "    text = text.lower()\n",
    "\n",
    "    # Remove HTML tags\n",
    "    text = re.sub(r\"<.*?>\", \" \", text)\n",
    "\n",
    "    # Remove URLs\n",
    "    text = re.sub(r\"http\\S+|www\\S+\", \" \", text)\n",
    "\n",
    "    # Remove email addresses\n",
    "    text = re.sub(r\"\\S+@\\S+\", \" \", text)\n",
    "\n",
    "    # Remove punctuation\n",
    "    text = text.translate(\n",
    "        str.maketrans(\"\", \"\", string.punctuation)\n",
    "    )\n",
    "\n",
    "    # Remove extra whitespace\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "\n",
    "    # Remove leading and trailing spaces\n",
    "    text = text.strip()\n",
    "\n",
    "    return text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "83da0b0a-2e0c-400f-9e0c-74b4b5aeb679",
   "metadata": {},
   "outputs": [],
   "source": [
    "# BM25 Tokenization\n",
    "# =============================================================================\n",
    "# Load English stopwords\n",
    "# =============================================================================\n",
    "\n",
    "stop_words = set(stopwords.words(\"english\"))\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# Prepare text for BM25 indexing\n",
    "# =============================================================================\n",
    "\n",
    "def preprocess_bm25(text):\n",
    "    \"\"\"\n",
    "    Clean, tokenize, and remove stopwords for BM25.\n",
    "    \"\"\"\n",
    "\n",
    "    # Apply lexical cleaning\n",
    "    text = clean_text_bm25(text)\n",
    "\n",
    "    # Split into tokens\n",
    "    tokens = text.split()\n",
    "\n",
    "    # Remove stopwords\n",
    "    tokens = [\n",
    "        token\n",
    "        for token in tokens\n",
    "        if token not in stop_words]\n",
    "\n",
    "    # Join tokens into a single string\n",
    "    return \" \".join(tokens)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "8e4daf91-ff68-4862-966b-bd9d9396983c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>lexical_text</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>dimensions item</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>much booze hold poured booze measuring cup sun...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>case fit nokia lumia 520 yes fits great great ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>folded sitting position high ground seat 30 in...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>long leave get max sweat benefit keep thinking...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        lexical_text\n",
       "0                                   dimensions item \n",
       "1  much booze hold poured booze measuring cup sun...\n",
       "2  case fit nokia lumia 520 yes fits great great ...\n",
       "3  folded sitting position high ground seat 30 in...\n",
       "4  long leave get max sweat benefit keep thinking..."
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create BM25 Text\n",
    "# =============================================================================\n",
    "# Create lexical text for BM25 retrieval\n",
    "# =============================================================================\n",
    "\n",
    "dataset[\"lexical_text\"] = (\n",
    "    dataset[\"QuestionText\"].apply(preprocess_bm25)\n",
    "    + \" \"\n",
    "    + dataset[\"AnswerText\"].apply(preprocess_bm25))\n",
    "\n",
    "# Preview lexical text\n",
    "dataset[[\"lexical_text\"]].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "8aa65c90-77da-46a2-9c29-92ef77797c9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original Question\n",
      "- What are the dimensions of this item?\n",
      "\n",
      "Original Answer\n",
      "http://www.lockcorporationofamerica.com/products/specs/lca-specs.pdf\n",
      "\n",
      "Semantic Text\n",
      "Question: - what are the dimensions of this item?\n",
      "\n",
      "Answer: \n",
      "\n",
      "Lexical Text\n",
      "dimensions item \n"
     ]
    }
   ],
   "source": [
    "# =============================================================================\n",
    "# Compare original and processed text\n",
    "# =============================================================================\n",
    "\n",
    "sample = 0\n",
    "\n",
    "print(\"Original Question\")\n",
    "print(dataset.loc[sample, \"QuestionText\"])\n",
    "\n",
    "print(\"\\nOriginal Answer\")\n",
    "print(dataset.loc[sample, \"AnswerText\"])\n",
    "\n",
    "print(\"\\nSemantic Text\")\n",
    "print(dataset.loc[sample, \"semantic_text\"])\n",
    "\n",
    "print(\"\\nLexical Text\")\n",
    "print(dataset.loc[sample, \"lexical_text\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "7c507814-f82e-46f5-b75d-73d8e8d17017",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Preprocessed dataset saved successfully.\n"
     ]
    }
   ],
   "source": [
    "# =============================================================================\n",
    "# Save the preprocessed dataset\n",
    "# =============================================================================\n",
    "dataset.to_csv(\"preprocessed_dataset.csv\", index=False)\n",
    "\n",
    "print(\"Preprocessed dataset saved successfully.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
